# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/additional/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/additional

PRODUCT_COPY_FILES += \
    vendor/motorola/additional/proprietary/product/etc/default-permissions/default-permission-com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permission-com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/etc/permissions/com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.timeweatherwidget.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.timeweatherwidget.xml \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Chime.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Chime.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Clear.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Clear.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Element.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Element.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Hello.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Hello.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Ivory.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Ivory.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Moto.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Moto.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Natural.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Natural.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/notifications/Soft.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/notifications/Soft.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Attentive.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Attentive.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Hello.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Hello.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Momentum.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Momentum.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Moto.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Moto.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Natural.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Natural.ogg \
    vendor/motorola/additional/proprietary/product/media/audio/ringtones/Simple.ogg:$(TARGET_COPY_OUT_PRODUCT)/media/audio/ringtones/Simple.ogg \
    vendor/motorola/additional/proprietary/system/bin/dropboxhelper:$(TARGET_COPY_OUT_SYSTEM)/bin/dropboxhelper \
    vendor/motorola/additional/proprietary/system/etc/permissions/com.motorola.frameworks.core.addon.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.frameworks.core.addon.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/com.motorola.motosignature.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.motorola.motosignature.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-checkin.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-checkin.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-core_services.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-core_services.xml \
    vendor/motorola/additional/proprietary/system/etc/permissions/moto-settings.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/moto-settings.xml \
    vendor/motorola/additional/proprietary/system_ext/bin/motsettings:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/motsettings \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/afw-com.motorola.livewallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/afw-com.motorola.livewallpaper.xml \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/feature-com.motorola.motolivewallpaper3.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/feature-com.motorola.motolivewallpaper3.xml \
    vendor/motorola/additional/proprietary/system_ext/etc/permissions/privapp-permissions-com.motorola.livewallpaper.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-com.motorola.livewallpaper.xml

PRODUCT_PACKAGES += \
    MotoSignature2App \
    MotoSignatureApp \
    TimeWeather \
    MotoLauncher3QuickStep \
    MotoLiveWallpaper3 \
    MotorolaSettingsProvider \
    com.motorola.android.dropboxhelper \
    com.motorola.frameworks.core.addon \
    com.motorola.motosignature \
    moto-checkin \
    moto-core_services \
    moto-settings
